# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 18:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [(b'integration', '0002_auto_20170629_0645'),
                (b'integration', '0003_auto_20170630_1947'),
                (b'integration', '0004_auto_20170718_1816')]

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.AddField(
            model_name='category',
            name='reference',
            field=models.SlugField(default='-', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='reference',
            field=models.SlugField(default='-', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='children',
                                    to='integration.Category'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterIndexTogether(
            name='category',
            index_together=set([('reference',)]),
        ),
        migrations.AlterIndexTogether(
            name='channel',
            index_together=set([('reference',)]),
        ),
    ]
