# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_auto_20170629_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='reference',
            field=models.SlugField(default='-', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='reference',
            field=models.SlugField(default='-', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='children', to='integration.Category'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
